[package]
name = "cairo-debugger"
version = "0.1.0"
edition = "2024"

[dependencies]
dap = { git = "https://github.com/software-mansion-labs/dap-rs", rev = "4440a6f" }
cairo-vm = { git = "https://github.com/software-mansion-labs/cairo-vm", rev = "e8183f4" }
tracing = "0.1"
anyhow = "1.0"
